// Auto-generated Fuzzy Controller from ../FIS_RULES/mpptfuzzy.fis
// Generated by MATLAB FIS to SV converter

module fuzzy_controller (
    input  real DV,
    input  real DI,
    output real DO,
    input  clk
);

    // DV membership functions
    function real DV_NB;
        input real x;
        DV_NB = trimf(x, -1.277778, -1.000000, -0.722222);
    endfunction

    function real DV_NM;
        input real x;
        DV_NM = trimf(x, -0.944444, -0.666667, -0.388889);
    endfunction

    function real DV_NS;
        input real x;
        DV_NS = trimf(x, -0.611111, -0.333333, -0.055556);
    endfunction

    function real DV_ZE;
        input real x;
        DV_ZE = trimf(x, -0.277778, -0.000000, 0.277778);
    endfunction

    function real DV_PS;
        input real x;
        DV_PS = trimf(x, 0.055556, 0.333333, 0.611111);
    endfunction

    function real DV_PM;
        input real x;
        DV_PM = trimf(x, 0.388889, 0.666667, 0.944444);
    endfunction

    function real DV_PB;
        input real x;
        DV_PB = trimf(x, 0.722222, 1.000000, 1.277778);
    endfunction

    // DI membership functions
    function real DI_NB;
        input real x;
        DI_NB = trimf(x, -12.777778, -10.000000, -7.222222);
    endfunction

    function real DI_NM;
        input real x;
        DI_NM = trimf(x, -9.444444, -6.666667, -3.888889);
    endfunction

    function real DI_NS;
        input real x;
        DI_NS = trimf(x, -6.111111, -3.333333, -0.555556);
    endfunction

    function real DI_ZE;
        input real x;
        DI_ZE = trimf(x, -2.777778, 0.000000, 2.777778);
    endfunction

    function real DI_PS;
        input real x;
        DI_PS = trimf(x, 0.555556, 3.333333, 6.111111);
    endfunction

    function real DI_PM;
        input real x;
        DI_PM = trimf(x, 3.888889, 6.666667, 9.444444);
    endfunction

    function real DI_PB;
        input real x;
        DI_PB = trimf(x, 7.222222, 10.000000, 12.777778);
    endfunction

    // Rule evaluation
    real rule_strength [49];

    always @(posedge clk) begin
        // Rule 1: IF DV_NB(DV) AND DI_NB(DI) THEN DO is NB
        rule_strength[0] = min('{DV_NB(DV), DI_NB(DI)});
        // Rule 2: IF DV_NM(DV) AND DI_NB(DI) THEN DO is NB
        rule_strength[1] = min('{DV_NM(DV), DI_NB(DI)});
        // Rule 3: IF DV_NS(DV) AND DI_NB(DI) THEN DO is NM
        rule_strength[2] = min('{DV_NS(DV), DI_NB(DI)});
        // Rule 4: IF DV_ZE(DV) AND DI_NB(DI) THEN DO is PS
        rule_strength[3] = min('{DV_ZE(DV), DI_NB(DI)});
        // Rule 5: IF DV_PS(DV) AND DI_NB(DI) THEN DO is PM
        rule_strength[4] = min('{DV_PS(DV), DI_NB(DI)});
        // Rule 6: IF DV_PM(DV) AND DI_NB(DI) THEN DO is PB
        rule_strength[5] = min('{DV_PM(DV), DI_NB(DI)});
        // Rule 7: IF DV_PB(DV) AND DI_NB(DI) THEN DO is PB
        rule_strength[6] = min('{DV_PB(DV), DI_NB(DI)});
        // Rule 8: IF DV_NB(DV) AND DI_NM(DI) THEN DO is NB
        rule_strength[7] = min('{DV_NB(DV), DI_NM(DI)});
        // Rule 9: IF DV_NM(DV) AND DI_NM(DI) THEN DO is NM
        rule_strength[8] = min('{DV_NM(DV), DI_NM(DI)});
        // Rule 10: IF DV_NS(DV) AND DI_NM(DI) THEN DO is NM
        rule_strength[9] = min('{DV_NS(DV), DI_NM(DI)});
        // Rule 11: IF DV_ZE(DV) AND DI_NM(DI) THEN DO is PS
        rule_strength[10] = min('{DV_ZE(DV), DI_NM(DI)});
        // Rule 12: IF DV_PS(DV) AND DI_NM(DI) THEN DO is PM
        rule_strength[11] = min('{DV_PS(DV), DI_NM(DI)});
        // Rule 13: IF DV_PM(DV) AND DI_NM(DI) THEN DO is PM
        rule_strength[12] = min('{DV_PM(DV), DI_NM(DI)});
        // Rule 14: IF DV_PB(DV) AND DI_NM(DI) THEN DO is PB
        rule_strength[13] = min('{DV_PB(DV), DI_NM(DI)});
        // Rule 15: IF DV_NB(DV) AND DI_NS(DI) THEN DO is NM
        rule_strength[14] = min('{DV_NB(DV), DI_NS(DI)});
        // Rule 16: IF DV_NM(DV) AND DI_NS(DI) THEN DO is NM
        rule_strength[15] = min('{DV_NM(DV), DI_NS(DI)});
        // Rule 17: IF DV_NS(DV) AND DI_NS(DI) THEN DO is NS
        rule_strength[16] = min('{DV_NS(DV), DI_NS(DI)});
        // Rule 18: IF DV_ZE(DV) AND DI_NS(DI) THEN DO is PS
        rule_strength[17] = min('{DV_ZE(DV), DI_NS(DI)});
        // Rule 19: IF DV_PS(DV) AND DI_NS(DI) THEN DO is PS
        rule_strength[18] = min('{DV_PS(DV), DI_NS(DI)});
        // Rule 20: IF DV_PM(DV) AND DI_NS(DI) THEN DO is PM
        rule_strength[19] = min('{DV_PM(DV), DI_NS(DI)});
        // Rule 21: IF DV_PB(DV) AND DI_NS(DI) THEN DO is PM
        rule_strength[20] = min('{DV_PB(DV), DI_NS(DI)});
        // Rule 22: IF DV_NB(DV) AND DI_ZE(DI) THEN DO is NS
        rule_strength[21] = min('{DV_NB(DV), DI_ZE(DI)});
        // Rule 23: IF DV_NM(DV) AND DI_ZE(DI) THEN DO is NS
        rule_strength[22] = min('{DV_NM(DV), DI_ZE(DI)});
        // Rule 24: IF DV_NS(DV) AND DI_ZE(DI) THEN DO is NS
        rule_strength[23] = min('{DV_NS(DV), DI_ZE(DI)});
        // Rule 25: IF DV_ZE(DV) AND DI_ZE(DI) THEN DO is ZE
        rule_strength[24] = min('{DV_ZE(DV), DI_ZE(DI)});
        // Rule 26: IF DV_PS(DV) AND DI_ZE(DI) THEN DO is PS
        rule_strength[25] = min('{DV_PS(DV), DI_ZE(DI)});
        // Rule 27: IF DV_PM(DV) AND DI_ZE(DI) THEN DO is PS
        rule_strength[26] = min('{DV_PM(DV), DI_ZE(DI)});
        // Rule 28: IF DV_PB(DV) AND DI_ZE(DI) THEN DO is PS
        rule_strength[27] = min('{DV_PB(DV), DI_ZE(DI)});
        // Rule 29: IF DV_NB(DV) AND DI_PS(DI) THEN DO is PM
        rule_strength[28] = min('{DV_NB(DV), DI_PS(DI)});
        // Rule 30: IF DV_NM(DV) AND DI_PS(DI) THEN DO is PM
        rule_strength[29] = min('{DV_NM(DV), DI_PS(DI)});
        // Rule 31: IF DV_NS(DV) AND DI_PS(DI) THEN DO is PS
        rule_strength[30] = min('{DV_NS(DV), DI_PS(DI)});
        // Rule 32: IF DV_ZE(DV) AND DI_PS(DI) THEN DO is NS
        rule_strength[31] = min('{DV_ZE(DV), DI_PS(DI)});
        // Rule 33: IF DV_PS(DV) AND DI_PS(DI) THEN DO is NS
        rule_strength[32] = min('{DV_PS(DV), DI_PS(DI)});
        // Rule 34: IF DV_PM(DV) AND DI_PS(DI) THEN DO is NM
        rule_strength[33] = min('{DV_PM(DV), DI_PS(DI)});
        // Rule 35: IF DV_PB(DV) AND DI_PS(DI) THEN DO is NM
        rule_strength[34] = min('{DV_PB(DV), DI_PS(DI)});
        // Rule 36: IF DV_NB(DV) AND DI_PM(DI) THEN DO is PB
        rule_strength[35] = min('{DV_NB(DV), DI_PM(DI)});
        // Rule 37: IF DV_NM(DV) AND DI_PM(DI) THEN DO is PM
        rule_strength[36] = min('{DV_NM(DV), DI_PM(DI)});
        // Rule 38: IF DV_NS(DV) AND DI_PM(DI) THEN DO is PM
        rule_strength[37] = min('{DV_NS(DV), DI_PM(DI)});
        // Rule 39: IF DV_ZE(DV) AND DI_PM(DI) THEN DO is NS
        rule_strength[38] = min('{DV_ZE(DV), DI_PM(DI)});
        // Rule 40: IF DV_PS(DV) AND DI_PM(DI) THEN DO is NM
        rule_strength[39] = min('{DV_PS(DV), DI_PM(DI)});
        // Rule 41: IF DV_PM(DV) AND DI_PM(DI) THEN DO is NM
        rule_strength[40] = min('{DV_PM(DV), DI_PM(DI)});
        // Rule 42: IF DV_PB(DV) AND DI_PM(DI) THEN DO is NB
        rule_strength[41] = min('{DV_PB(DV), DI_PM(DI)});
        // Rule 43: IF DV_NB(DV) AND DI_PB(DI) THEN DO is PB
        rule_strength[42] = min('{DV_NB(DV), DI_PB(DI)});
        // Rule 44: IF DV_NM(DV) AND DI_PB(DI) THEN DO is PB
        rule_strength[43] = min('{DV_NM(DV), DI_PB(DI)});
        // Rule 45: IF DV_NS(DV) AND DI_PB(DI) THEN DO is PM
        rule_strength[44] = min('{DV_NS(DV), DI_PB(DI)});
        // Rule 46: IF DV_ZE(DV) AND DI_PB(DI) THEN DO is NS
        rule_strength[45] = min('{DV_ZE(DV), DI_PB(DI)});
        // Rule 47: IF DV_PS(DV) AND DI_PB(DI) THEN DO is NM
        rule_strength[46] = min('{DV_PS(DV), DI_PB(DI)});
        // Rule 48: IF DV_PM(DV) AND DI_PB(DI) THEN DO is NB
        rule_strength[47] = min('{DV_PM(DV), DI_PB(DI)});
        // Rule 49: IF DV_PB(DV) AND DI_PB(DI) THEN DO is NB
        rule_strength[48] = min('{DV_PB(DV), DI_PB(DI)});

        // Defuzzification - Center of Gravity
        real numerator = 0.0;
        real denominator = 0.0;
        
        numerator = numerator + rule_strength[0] * -0.091398;
        denominator = denominator + rule_strength[0];
        numerator = numerator + rule_strength[1] * -0.091398;
        denominator = denominator + rule_strength[1];
        numerator = numerator + rule_strength[2] * -0.066661;
        denominator = denominator + rule_strength[2];
        numerator = numerator + rule_strength[3] * 0.033339;
        denominator = denominator + rule_strength[3];
        numerator = numerator + rule_strength[4] * 0.066661;
        denominator = denominator + rule_strength[4];
        numerator = numerator + rule_strength[5] * 0.091398;
        denominator = denominator + rule_strength[5];
        numerator = numerator + rule_strength[6] * 0.091398;
        denominator = denominator + rule_strength[6];
        numerator = numerator + rule_strength[7] * -0.091398;
        denominator = denominator + rule_strength[7];
        numerator = numerator + rule_strength[8] * -0.066661;
        denominator = denominator + rule_strength[8];
        numerator = numerator + rule_strength[9] * -0.066661;
        denominator = denominator + rule_strength[9];
        numerator = numerator + rule_strength[10] * 0.033339;
        denominator = denominator + rule_strength[10];
        numerator = numerator + rule_strength[11] * 0.066661;
        denominator = denominator + rule_strength[11];
        numerator = numerator + rule_strength[12] * 0.066661;
        denominator = denominator + rule_strength[12];
        numerator = numerator + rule_strength[13] * 0.091398;
        denominator = denominator + rule_strength[13];
        numerator = numerator + rule_strength[14] * -0.066661;
        denominator = denominator + rule_strength[14];
        numerator = numerator + rule_strength[15] * -0.066661;
        denominator = denominator + rule_strength[15];
        numerator = numerator + rule_strength[16] * -0.033339;
        denominator = denominator + rule_strength[16];
        numerator = numerator + rule_strength[17] * 0.033339;
        denominator = denominator + rule_strength[17];
        numerator = numerator + rule_strength[18] * 0.033339;
        denominator = denominator + rule_strength[18];
        numerator = numerator + rule_strength[19] * 0.066661;
        denominator = denominator + rule_strength[19];
        numerator = numerator + rule_strength[20] * 0.066661;
        denominator = denominator + rule_strength[20];
        numerator = numerator + rule_strength[21] * -0.033339;
        denominator = denominator + rule_strength[21];
        numerator = numerator + rule_strength[22] * -0.033339;
        denominator = denominator + rule_strength[22];
        numerator = numerator + rule_strength[23] * -0.033339;
        denominator = denominator + rule_strength[23];
        numerator = numerator + rule_strength[24] * -0.000000;
        denominator = denominator + rule_strength[24];
        numerator = numerator + rule_strength[25] * 0.033339;
        denominator = denominator + rule_strength[25];
        numerator = numerator + rule_strength[26] * 0.033339;
        denominator = denominator + rule_strength[26];
        numerator = numerator + rule_strength[27] * 0.033339;
        denominator = denominator + rule_strength[27];
        numerator = numerator + rule_strength[28] * 0.066661;
        denominator = denominator + rule_strength[28];
        numerator = numerator + rule_strength[29] * 0.066661;
        denominator = denominator + rule_strength[29];
        numerator = numerator + rule_strength[30] * 0.033339;
        denominator = denominator + rule_strength[30];
        numerator = numerator + rule_strength[31] * -0.033339;
        denominator = denominator + rule_strength[31];
        numerator = numerator + rule_strength[32] * -0.033339;
        denominator = denominator + rule_strength[32];
        numerator = numerator + rule_strength[33] * -0.066661;
        denominator = denominator + rule_strength[33];
        numerator = numerator + rule_strength[34] * -0.066661;
        denominator = denominator + rule_strength[34];
        numerator = numerator + rule_strength[35] * 0.091398;
        denominator = denominator + rule_strength[35];
        numerator = numerator + rule_strength[36] * 0.066661;
        denominator = denominator + rule_strength[36];
        numerator = numerator + rule_strength[37] * 0.066661;
        denominator = denominator + rule_strength[37];
        numerator = numerator + rule_strength[38] * -0.033339;
        denominator = denominator + rule_strength[38];
        numerator = numerator + rule_strength[39] * -0.066661;
        denominator = denominator + rule_strength[39];
        numerator = numerator + rule_strength[40] * -0.066661;
        denominator = denominator + rule_strength[40];
        numerator = numerator + rule_strength[41] * -0.091398;
        denominator = denominator + rule_strength[41];
        numerator = numerator + rule_strength[42] * 0.091398;
        denominator = denominator + rule_strength[42];
        numerator = numerator + rule_strength[43] * 0.091398;
        denominator = denominator + rule_strength[43];
        numerator = numerator + rule_strength[44] * 0.066661;
        denominator = denominator + rule_strength[44];
        numerator = numerator + rule_strength[45] * -0.033339;
        denominator = denominator + rule_strength[45];
        numerator = numerator + rule_strength[46] * -0.066661;
        denominator = denominator + rule_strength[46];
        numerator = numerator + rule_strength[47] * -0.091398;
        denominator = denominator + rule_strength[47];
        numerator = numerator + rule_strength[48] * -0.091398;
        denominator = denominator + rule_strength[48];
        
        if (denominator > 1e-9) begin
            DO = numerator / denominator;
        end else begin
            DO = 0.0;
        end
    end

    // Membership function helpers
    function real trimf;
        input real x, a, b, c;
        begin
            if (x <= a || x >= c) trimf = 0.0;
            else if (x <= b) trimf = (x - a) / (b - a);
            else trimf = (c - x) / (c - b);
        end
    endfunction

    function real trapmf;
        input real x, a, b, c, d;
        begin
            if (x <= a || x >= d) trapmf = 0.0;
            else if (x >= b && x <= c) trapmf = 1.0;
            else if (x <= b) trapmf = (x - a) / (b - a);
            else trapmf = (d - x) / (d - c);
        end
    endfunction

    function real gaussmf;
        input real x, sigma, c;
        begin
            gaussmf = exp(-((x - c) * (x - c)) / (2.0 * sigma * sigma));
        end
    endfunction

    function real gbellmf;
        input real x, a, b, c;
        begin
            gbellmf = 1.0 / (1.0 + pow(abs((x - c) / a), 2.0 * b));
        end
    endfunction

    function real min;
        input real vals[];
        real result;
        begin
            result = vals[0];
            for (int i = 1; i < vals.size(); i++) begin
                if (vals[i] < result) result = vals[i];
            end
            min = result;
        end
    endfunction

endmodule
